export const SET_POSITIONS = "SET_POSITIONS";
export const SET_MEANTIME_EMPLOYEES = "SET_MEANTIME_EMPLOYEES";
export const ADD_MEANTIME_EMPLOYEES = "ADD_MEANTIME_EMPLOYEES";
export const PUT_MEANTIME_EMPLOYEES = "PUT_MEANTIME_EMPLOYEES";